# Generated by Django 4.2.1 on 2023-06-21 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Дата и время индивидувльного занятия',
                'verbose_name_plural': 'Дата и время индивидувльного занятия',
                'db_table': 'app_datetime',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локация',
                'db_table': 'app_location',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия тренера')),
                ('photo', models.ImageField(blank=True, upload_to='images/news/tutor/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Фото тренера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'app_news',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_footer', models.TextField(blank=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Уведомления',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'app_notifications',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Наименование команды',
                'verbose_name_plural': 'Наименование команды',
                'db_table': 'app_team',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия тренера')),
            ],
            options={
                'verbose_name': 'Тренеры',
                'verbose_name_plural': 'Тренеры',
                'db_table': 'app_tutor',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('date_training', models.DateField(verbose_name='Дата тренировки')),
                ('start_training', models.TimeField(verbose_name='Начало тренировки')),
                ('finish_training', models.TimeField(verbose_name='Конец тренировки')),
                ('location_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tutor')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'db_table': 'app_schedule',
                'ordering': ('team',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('photo', models.ImageField(blank=True, default='images/avatars/default.jpg', upload_to='images/avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'app_profiles',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/news/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news')),
            ],
            options={
                'verbose_name': 'Фото для новостей',
                'verbose_name_plural': 'Фото для новостей',
                'db_table': 'app_news_image',
            },
        ),
        migrations.CreateModel(
            name='Indiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('child_name', models.CharField(max_length=255, verbose_name='Имя и фамилия ребенка')),
                ('datetime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.datetime', verbose_name='Дата и время индивидуального занятия')),
                ('location_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Локация')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tutor', verbose_name='Тренер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на индивидуальные занятия',
                'verbose_name_plural': 'Запись на индивидуальные занятия',
                'db_table': 'app_indiv',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, default='documents/insurance/default.pdf', upload_to='documents/insurance/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Страховка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
                'db_table': 'app_documents',
                'ordering': ('user',),
            },
        ),
    ]
